# Reference: https://www.mkdocs.org/user-guide/configuration/
docs_dir: "./mkdocs"
extra_javascript:
    - "https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js"
markdown_extensions:
    # https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/admonition/
    - pymdownx.blocks.admonition
    # https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
    - pymdownx.highlight:
          anchor_linenums: true
    # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
    - pymdownx.superfences
    # https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
    - pymdownx.smartsymbols
    # https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/
    - pymdownx.tasklist
nav:
    - "Home": "index.md"
    - "Basics":
          - "Getting Started": "getting-started.md"
          - "Terminology": "terminology.md"
          - "Common Workflows":
                - "Dataset downloads": "common-workflows/dataset-downloads.md"
    - "Changelog": "changelog.md"
    - "Advanced":
          - "Concurrent Access": "advanced/concurrent-access.md"
    - "API Reference":
          - "Client": "api/client.md"
          - "Errors": "api/errors.md"
          - "Captures": "api/captures.md"
          - "Datasets": "api/datasets.md"
          - "Models": "api/models.md"
          - "SDS Files": "api/sds_files.md"
          - "Operations":
                - "Pagination": "api/ops/pagination.md"
    - "Contributing":
          - "Contributing": "dev-notes/contributing.md"
          - "Design Notes": "dev-notes/dev-notes.md"
    - "FAQ": "faq.md"
plugins:
    - autorefs
    - search
    - mkdocstrings:
          enabled: true
          # custom_templates: templates
          default_handler: "python"
          locale: "en"
          handlers:
              python:
                  paths: ["spectrumx"]
                  options:
                      # https://mkdocstrings.github.io/python/usage/configuration/general/
                      backlinks: "tree" # "flat" | "tree" | False
                      inheritance_diagram_direction: "TD" # "TD" | "LR" | "BT" | "RL"
                      show_bases: true
                      show_inheritance_diagram: true
                      show_source: true

                      # https://mkdocstrings.github.io/python/usage/configuration/signatures/
                      annotations_path: "brief" # "full" | "brief" | "source"
                      line_length: 60
                      separate_signature: true
                      show_overloads: true
                      show_signature_annotations: true
                      show_signature_type_parameters: false
                      show_signature: true
                      signature_crossrefs: true
                      unwrap_annotated: false

                      # https://mkdocstrings.github.io/python/usage/configuration/headings/
                      heading_level: 3
                      parameter_headings: false
                      show_category_heading: true
                      show_object_full_path: false
                      show_root_full_path: true
                      show_root_heading: true
                      show_root_toc_entry: true
                      show_symbol_type_heading: true
                      show_symbol_type_toc: true
                      type_parameter_headings: true

                      # https://mkdocstrings.github.io/python/usage/configuration/members/
                      filters: ["!^_"]
                      group_by_category: true
                      inherited_members: true
                      members_order: "alphabetical" # "alphabetical" | "source"
                      show_labels: true
                      show_submodules: false
                      summary: true

                      # Docstrings
                      # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_docstring_attributes
                      docstring_options:
                          ignore_init_summary: true
                      docstring_section_style: "table" # "list" | "table" | "spacy"
                      docstring_style: "google"
                      merge_init_into_class: true
                      show_docstring_attributes: true
                      show_docstring_classes: true
                      show_docstring_description: true
                      show_docstring_examples: true
                      show_docstring_functions: true
                      show_docstring_modules: true
                      show_docstring_other_parameters: true
                      show_docstring_parameters: true
                      show_docstring_type_aliases: true
                      show_docstring_raises: true
                      show_docstring_receives: true
                      show_docstring_returns: true
                      show_docstring_type_parameters: true
                      show_docstring_warns: true
                      show_docstring_yields: true
                      show_if_no_docstring: false

repo_name: "GitHub | SpectrumX Python SDK"
repo_url: "https://github.com/spectrumx/sds-code/tree/master/sdk/"
site_author: "SpectrumX | Center for Research Computing | University of Notre Dame"
site_name: "SpectrumX Python SDK"
site_url: "https://sds.crc.nd.edu/sdk/"
theme:
    # material theme customization:
    # https://squidfunk.github.io/mkdocs-material/customization/
    features:
        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
        - navigation.expand
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.path
        - navigation.tracking
        # - navigation.tabs
        # - navigation.tabs.sticky
        # - toc.integrate
    font:
        text: "Exo 2"
        code: "Inconsolata"
    name: "material"
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
              icon: "material/brightness-auto"
              name: "Switch to light mode"
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: "default"
          toggle:
              icon: "material/brightness-7"
              name: "Switch to dark mode"
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: "slate"
          toggle:
              icon: "material/brightness-4"
              name: "Switch to system preference"
validation:
    omitted_files: "warn"
    absolute_links: "warn" # or 'relative_to_docs'
    unrecognized_links: "warn"
    anchors: "warn"
